### ISSUE TITLE
Inspector in JupyterLab

### ISSUE THREAD

**Issue by weaverba137** [sbailey/viproto-inspector#10]
NERSC's jupyter-dev is now using JupyterLab.  Several things seem to be broken:

* Buttons used to be above the plot, now they are below.
* Prev/Next buttons internally advance the object (you can see this by pressing Next, then pressing one of the other buttons, then displaying the `sp.visual_scan` table. However, the display does not get updated.
* Emission/absorption lines no longer display.
* The widget that is supposed to display object metadata is broken (only displays "Hello There").

**Comment by weaverba137** [comment]
PS, in JupyterLab, it is possible to "Launch Classic Notebook".  In such an environment, Inspector still works fine, except that buttons are still below the plot.

**Comment by sbailey** [comment]
In the short term we should update the README that it doesn't work with JupyterLab at NERSC, but that it does work with the classic interface, which you can access directly via a URL like https://jupyter-dev.nersc.gov/user/sjbailey/tree/global/homes/s/sjbailey (replace sjbailey with your username in two places in that URL).

I've been iterating with NERSC about what the fix is for Jupyter Lab.  Jupyter Lab now requires a bokeh plugin to be installed, which isn't required for the classic interface.  In a simple test case combining bokeh+ipywidgets, it appears to be a mismatch between the version of the bokeh plugin installed and the version of bokeh in our desiconda kernels (which is newer than the bokeh provided by NERSC python installations, so it isn't as simple as them just changing their plugin version).  Rollin is at a Jupyter conference this week and this is on his list of topics to discuss with the Jupyter Lab developers.  We'll do more testing when he is back and try to come up with a workaround.

I don't care about whether the buttons are above or below the plot, but I do care about the rest of the bugs you itemize.

**Comment by weaverba137** [comment]
OK, do you mind updating the README file?

**Comment by weaverba137** [comment]
I'm not convinced that simply updating the README actually *fixes* this bug.  I would recommend keeping it open until the JupyterLab issues are resolved.

**Comment by sbailey** [comment]
Good point.  Reopening.

**Comment by weaverba137** [comment]
No point in keeping this open since development on inspector has stopped.
